// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using SrednjeSkoleApp.Data.EF;
using System;

namespace SrednjeSkoleApp.Data.Migrations
{
    [DbContext(typeof(MojKontext))]
    partial class MojKontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Cas", b =>
                {
                    b.Property<int>("CasId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Datum");

                    b.Property<string>("Naslov");

                    b.Property<int>("NastavnikId");

                    b.Property<string>("opis");

                    b.HasKey("CasId");

                    b.HasIndex("NastavnikId");

                    b.ToTable("Casovi");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Izostanak", b =>
                {
                    b.Property<int>("IzostanakId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CasId");

                    b.Property<string>("Komentar");

                    b.Property<string>("Razlog");

                    b.Property<int>("UcenikId");

                    b.Property<int?>("UcenikKorisnikId");

                    b.HasKey("IzostanakId");

                    b.HasIndex("CasId");

                    b.HasIndex("UcenikId");

                    b.HasIndex("UcenikKorisnikId");

                    b.ToTable("Izostanci");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.KorisniciUloge", b =>
                {
                    b.Property<int>("KorisniciUlogeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("KorisnikID");

                    b.Property<int>("UlogaID");

                    b.HasKey("KorisniciUlogeId");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("UlogaID");

                    b.ToTable("KorisniciUloge");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Aktivan");

                    b.Property<DateTime>("DatumRodjenja");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Ime");

                    b.Property<string>("JMBG");

                    b.Property<string>("Lozinka");

                    b.Property<string>("MjestoRodjenja");

                    b.Property<string>("Prebivaliste");

                    b.Property<string>("Prezime");

                    b.Property<string>("Spol");

                    b.HasKey("KorisnikId");

                    b.ToTable("Korisnici");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Korisnik");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.KorisnikKontakt", b =>
                {
                    b.Property<int>("KorisnikKontaktId");

                    b.Property<string>("Adresa");

                    b.Property<string>("Email");

                    b.Property<string>("Grad");

                    b.Property<string>("Opstina");

                    b.Property<string>("Telefon");

                    b.HasKey("KorisnikKontaktId");

                    b.ToTable("KorisnikKontakt");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Materijal", b =>
                {
                    b.Property<int>("MaterijalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Napomena");

                    b.Property<int>("NastavnikId");

                    b.Property<string>("Naziv");

                    b.Property<int?>("SkolskaGodinaId");

                    b.HasKey("MaterijalId");

                    b.HasIndex("NastavnikId");

                    b.HasIndex("SkolskaGodinaId");

                    b.ToTable("Materijali");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Obavijest", b =>
                {
                    b.Property<int>("ObavijestID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("KorisnikID");

                    b.Property<string>("Naslov");

                    b.Property<string>("Tekst");

                    b.HasKey("ObavijestID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Obavijesti");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Ocjena", b =>
                {
                    b.Property<int>("OcjenaId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Datum");

                    b.Property<string>("Napomena");

                    b.Property<string>("TipOcjene");

                    b.Property<int>("UcenikPredmetId");

                    b.Property<int>("Vrijednost");

                    b.HasKey("OcjenaId");

                    b.HasIndex("UcenikPredmetId");

                    b.ToTable("Ocjene");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Predaje", b =>
                {
                    b.Property<int>("PredajeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NastavnikId");

                    b.Property<int>("RazredId");

                    b.Property<bool>("Razrednik");

                    b.Property<int>("SkolskaGodinaId");

                    b.Property<int>("SmjerPredmetId");

                    b.HasKey("PredajeId");

                    b.HasIndex("NastavnikId");

                    b.HasIndex("RazredId");

                    b.HasIndex("SkolskaGodinaId");

                    b.HasIndex("SmjerPredmetId");

                    b.ToTable("Predaje");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Predmet", b =>
                {
                    b.Property<int>("PredmetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Naziv");

                    b.Property<string>("Oznaka");

                    b.HasKey("PredmetId");

                    b.ToTable("Predmet");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.PredmetiNaSmjeru", b =>
                {
                    b.Property<int>("PredmetiNaSmjeruId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PredmetId");

                    b.Property<int>("SmjerId");

                    b.Property<int?>("SmjerPredmetId");

                    b.HasKey("PredmetiNaSmjeruId");

                    b.HasIndex("PredmetId");

                    b.HasIndex("SmjerId");

                    b.HasIndex("SmjerPredmetId");

                    b.ToTable("PredmetiNaSmjeru");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Razred", b =>
                {
                    b.Property<int>("RazredId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Odjeljenje");

                    b.Property<string>("Oznaka");

                    b.HasKey("RazredId");

                    b.ToTable("Razred");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.SkolskaGodina", b =>
                {
                    b.Property<int>("SkolskaGodinaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Naziv");

                    b.HasKey("SkolskaGodinaId");

                    b.ToTable("SkolskaGodina");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Smjer", b =>
                {
                    b.Property<int>("SmjerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Naziv");

                    b.Property<string>("Opis");

                    b.Property<int?>("SkolskaGodinaId");

                    b.HasKey("SmjerId");

                    b.HasIndex("SkolskaGodinaId");

                    b.ToTable("Smjerovi");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.SmjerPredmet", b =>
                {
                    b.Property<int>("SmjerPredmetId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrojCasova");

                    b.Property<double?>("ProsjecnaOcjena");

                    b.HasKey("SmjerPredmetId");

                    b.ToTable("SmjerPredmet");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.UcenikCasovi", b =>
                {
                    b.Property<int>("UcenikCasoviId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CasId");

                    b.Property<int?>("CasId1");

                    b.Property<int>("UcenikId");

                    b.Property<int?>("UcenikKorisnikId");

                    b.HasKey("UcenikCasoviId");

                    b.HasIndex("CasId");

                    b.HasIndex("CasId1");

                    b.HasIndex("UcenikId");

                    b.HasIndex("UcenikKorisnikId");

                    b.ToTable("UceniciCasovi");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.UcenikPredmet", b =>
                {
                    b.Property<int>("UcenikPredmetId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UcenikId");

                    b.Property<double?>("ZakljucnaOcjena");

                    b.HasKey("UcenikPredmetId");

                    b.HasIndex("UcenikId");

                    b.ToTable("UceniciPredmeti");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.UcenikRazredi", b =>
                {
                    b.Property<int>("UcenikRazrediId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RazredId");

                    b.Property<int>("RedniBroj");

                    b.Property<int?>("SkolskaGodinaId");

                    b.Property<int>("UcenikId");

                    b.HasKey("UcenikRazrediId");

                    b.HasIndex("RazredId");

                    b.HasIndex("SkolskaGodinaId");

                    b.HasIndex("UcenikId");

                    b.ToTable("UceniciRazredi");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Administrator");

                    b.Property<bool>("Nastavnik");

                    b.Property<string>("Naziv");

                    b.Property<bool>("Roditelj");

                    b.Property<bool>("Ucenik");

                    b.HasKey("UlogaId");

                    b.ToTable("Uloge");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Nastavnik", b =>
                {
                    b.HasBaseType("SrednjeSkoleApp.Data.Models.Korisnik");

                    b.Property<DateTime>("DatumIzboraUZvanje");

                    b.Property<int>("GodinaZaposlenja");

                    b.Property<string>("NaucnaOblast");

                    b.Property<string>("Zvanje");

                    b.ToTable("Nastavnik");

                    b.HasDiscriminator().HasValue("Nastavnik");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Ucenik", b =>
                {
                    b.HasBaseType("SrednjeSkoleApp.Data.Models.Korisnik");

                    b.Property<int>("GodinaUpisa");

                    b.Property<string>("ImeRoditelja");

                    b.Property<int>("SmjerId");

                    b.HasIndex("SmjerId");

                    b.ToTable("Ucenik");

                    b.HasDiscriminator().HasValue("Ucenik");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Cas", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Nastavnik", "Nastavnik")
                        .WithMany("Cas")
                        .HasForeignKey("NastavnikId")
                        .OnDelete(DeleteBehavior.Cascade);
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Izostanak", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Cas", "Cas")
                        .WithMany("Izostanci")
                        .HasForeignKey("CasId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SrednjeSkoleApp.Data.Models.Ucenik", "Ucenik")
                        .WithMany()
                        .HasForeignKey("UcenikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SrednjeSkoleApp.Data.Models.Ucenik")
                        .WithMany("Izostanci")
                        .HasForeignKey("UcenikKorisnikId");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.KorisniciUloge", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Korisnik", "Korisnik")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SrednjeSkoleApp.Data.Models.Uloga", "Uloga")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("UlogaID")
                        .OnDelete(DeleteBehavior.Cascade);
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.KorisnikKontakt", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Korisnik", "Korisnik")
                        .WithOne("Kontakt")
                        .HasForeignKey("SrednjeSkoleApp.Data.Models.KorisnikKontakt", "KorisnikKontaktId")
                        .OnDelete(DeleteBehavior.Cascade);
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Materijal", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Nastavnik", "Nastavnik")
                        .WithMany("Materijali")
                        .HasForeignKey("NastavnikId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SrednjeSkoleApp.Data.Models.SkolskaGodina", "SkolskaGodina")
                        .WithMany()
                        .HasForeignKey("SkolskaGodinaId");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Obavijest", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Korisnik", "Korisnik")
                        .WithMany("Obavijesti")
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade);
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Ocjena", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.UcenikPredmet", "UcenikPredmet")
                        .WithMany("Ocjene")
                        .HasForeignKey("UcenikPredmetId")
                        .OnDelete(DeleteBehavior.Cascade);
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Predaje", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Nastavnik", "Nastavnik")
                        .WithMany("Predaje")
                        .HasForeignKey("NastavnikId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SrednjeSkoleApp.Data.Models.Razred", "Razred")
                        .WithMany("Predaje")
                        .HasForeignKey("RazredId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SrednjeSkoleApp.Data.Models.SkolskaGodina", "SkolskaGodina")
                        .WithMany("Predaje")
                        .HasForeignKey("SkolskaGodinaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SrednjeSkoleApp.Data.Models.SmjerPredmet", "SmjerPredmet")
                        .WithMany()
                        .HasForeignKey("SmjerPredmetId")
                        .OnDelete(DeleteBehavior.Cascade);
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.PredmetiNaSmjeru", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Predmet", "Predmet")
                        .WithMany("PredmetiNaSmjeru")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SrednjeSkoleApp.Data.Models.Smjer", "Smjer")
                        .WithMany()
                        .HasForeignKey("SmjerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SrednjeSkoleApp.Data.Models.SmjerPredmet")
                        .WithMany("PredmetiNaSmjeru")
                        .HasForeignKey("SmjerPredmetId");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Smjer", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.SkolskaGodina", "SkolskaGodina")
                        .WithMany()
                        .HasForeignKey("SkolskaGodinaId");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.UcenikCasovi", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Cas", "Cas")
                        .WithMany()
                        .HasForeignKey("CasId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SrednjeSkoleApp.Data.Models.Cas")
                        .WithMany("UcenikCasovi")
                        .HasForeignKey("CasId1");

                    b.HasOne("SrednjeSkoleApp.Data.Models.Ucenik", "Ucenik")
                        .WithMany()
                        .HasForeignKey("UcenikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SrednjeSkoleApp.Data.Models.Ucenik")
                        .WithMany("UcenikCasovi")
                        .HasForeignKey("UcenikKorisnikId");
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.UcenikPredmet", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Ucenik", "Ucenik")
                        .WithMany("UcenikPredmeti")
                        .HasForeignKey("UcenikId")
                        .OnDelete(DeleteBehavior.Cascade);
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.UcenikRazredi", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Razred", "Razred")
                        .WithMany("UcenikRazredi")
                        .HasForeignKey("RazredId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SrednjeSkoleApp.Data.Models.SkolskaGodina", "SkolskaGodina")
                        .WithMany()
                        .HasForeignKey("SkolskaGodinaId");

                    b.HasOne("SrednjeSkoleApp.Data.Models.Ucenik", "Ucenik")
                        .WithMany("UcenikRazredi")
                        .HasForeignKey("UcenikId")
                        .OnDelete(DeleteBehavior.Cascade);
            ***REMOVED***);

            modelBuilder.Entity("SrednjeSkoleApp.Data.Models.Ucenik", b =>
                {
                    b.HasOne("SrednjeSkoleApp.Data.Models.Smjer", "Smjer")
                        .WithMany("Ucenici")
                        .HasForeignKey("SmjerId")
                        .OnDelete(DeleteBehavior.Cascade);
            ***REMOVED***);
#pragma warning restore 612, 618
    ***REMOVED***
***REMOVED***
***REMOVED***
